### PR TITLE
PHP 8.0, type hints, PHPStan

### PR DESCRIPTION
**Pull request by adamzelycz**
This PR contributes to a new 3.0 version (#46)
- support for PHP 8.0+
- some annotations replaced by type hints
- updated PHPStan and fixed errors

### CODE REVIEW

**Comment by foxycode** [comment]
@h4kuna Looks good, when will you merge it? I'd like to prepare PR for `nette/utils` 4.0 support

**Comment by h4kuna** [comment]
Is in progress in this [branch](https://github.com/h4kuna/fio/tree/adamzelycz-master)

I have more points in plan.

**Comment by h4kuna** [comment]
Yesterday I prepared two libraries what i want to use. https://github.com/h4kuna/critical-cache and https://github.com/h4kuna/dir

**Comment by foxycode** [comment]
@h4kuna I understand using PSR instead of specific implementation, but why use another library when you could implement nete caching in `critical-cache`? You don't use nette any more?

**Comment by h4kuna** [comment]
The nette/caching is used by default in `critical-cache`, but it is not mandatory.  All dependenciees on nette I will keep in [fio-nette](//github.com/h4kuna/fio-nette)

**Comment by h4kuna** [comment]
- for create xml file i want to use php://memory, it means the cache is not need, maybe, only any mutex
- I wan't use raw \stdClass with this [anotation](https://youtrack.jetbrains.com/issue/WI-66396/Support-object-shape-generic-object-property-declaration), but phpstorm does not use in this moment

**Comment by h4kuna** [comment]
@foxycode if you have time, could you to make QA only Read is complete https://github.com/h4kuna/fio/compare/master...adamzelycz-master

**Comment by foxycode** [comment]
@h4kuna Working fine, updated README would be fine :)

**Pull request closed without merging**
