### PR TITLE
Renamed String class to Strings - fixes compatibility with php7

### PR DESCRIPTION
**Pull request by foxycode**
`String` is reserved word in PHP7

### CODE REVIEW

**Comment by h4kuna** [comment]
Nice work, could you remove "allow_failures" from .travis? For completly upgrade.

**Comment by foxycode** [comment]
@h4kuna Done

**Comment by h4kuna** [comment]
Thank you.

**Comment by foxycode** [comment]
@h4kuna No problem. Could you please make release?

**Comment by h4kuna** [comment]
@foxycode Done

**Pull request merged**
